HandleError<Route, fn(std::io::Error) -> impl Future<Output = impl IntoResponse> {handle_error}, _>
